/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as AutoavaliacaoRouteImport } from './routes/autoavaliacao'
import { Route as ConfiguracaoRouteImport } from './routes/configuracao'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as EnqueteRouteImport } from './routes/enquete'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as ModeracaoRouteImport } from './routes/moderacao'
import { Route as PercursoRouteImport } from './routes/percurso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as UnidadeRouteImport } from './routes/unidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoavaliacaoRoute = AutoavaliacaoRouteImport.update({
  id: '/autoavaliacao',
  path: '/autoavaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoRoute = ConfiguracaoRouteImport.update({
  id: '/configuracao',
  path: '/configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnqueteRoute = EnqueteRouteImport.update({
  id: '/enquete',
  path: '/enquete',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeracaoRoute = ModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PercursoRoute = PercursoRouteImport.update({
  id: '/percurso',
  path: '/percurso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadeRoute = UnidadeRouteImport.update({
  id: '/unidade',
  path: '/unidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/agenda': typeof AgendaRoute
  '/aulas': typeof AulasRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/conteudo': typeof ConteudoRoute
  '/enquete': typeof EnqueteRoute
  '/entrega': typeof EntregaRoute
  '/equipe': typeof EquipeRoute
  '/gestao': typeof GestaoRoute
  '/historico': typeof HistoricoRoute
  '/jornada': typeof JornadaRoute
  '/moderacao': typeof ModeracaoRoute
  '/percurso': typeof PercursoRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/unidade': typeof UnidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/agenda': typeof AgendaRoute
  '/aulas': typeof AulasRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/conteudo': typeof ConteudoRoute
  '/enquete': typeof EnqueteRoute
  '/entrega': typeof EntregaRoute
  '/equipe': typeof EquipeRoute
  '/gestao': typeof GestaoRoute
  '/historico': typeof HistoricoRoute
  '/jornada': typeof JornadaRoute
  '/moderacao': typeof ModeracaoRoute
  '/percurso': typeof PercursoRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/unidade': typeof UnidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/agenda': typeof AgendaRoute
  '/aulas': typeof AulasRoute
  '/autoavaliacao': typeof AutoavaliacaoRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/conteudo': typeof ConteudoRoute
  '/enquete': typeof EnqueteRoute
  '/entrega': typeof EntregaRoute
  '/equipe': typeof EquipeRoute
  '/gestao': typeof GestaoRoute
  '/historico': typeof HistoricoRoute
  '/jornada': typeof JornadaRoute
  '/moderacao': typeof ModeracaoRoute
  '/percurso': typeof PercursoRoute
  '/perfil': typeof PerfilRoute
  '/portfolio': typeof PortfolioRoute
  '/unidade': typeof UnidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/agenda'
    | '/aulas'
    | '/autoavaliacao'
    | '/configuracao'
    | '/conteudo'
    | '/enquete'
    | '/entrega'
    | '/equipe'
    | '/gestao'
    | '/historico'
    | '/jornada'
    | '/moderacao'
    | '/percurso'
    | '/perfil'
    | '/portfolio'
    | '/unidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/agenda'
    | '/aulas'
    | '/autoavaliacao'
    | '/configuracao'
    | '/conteudo'
    | '/enquete'
    | '/entrega'
    | '/equipe'
    | '/gestao'
    | '/historico'
    | '/jornada'
    | '/moderacao'
    | '/percurso'
    | '/perfil'
    | '/portfolio'
    | '/unidade'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/agenda'
    | '/aulas'
    | '/autoavaliacao'
    | '/configuracao'
    | '/conteudo'
    | '/enquete'
    | '/entrega'
    | '/equipe'
    | '/gestao'
    | '/historico'
    | '/jornada'
    | '/moderacao'
    | '/percurso'
    | '/perfil'
    | '/portfolio'
    | '/unidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  AgendaRoute: typeof AgendaRoute
  AulasRoute: typeof AulasRoute
  AutoavaliacaoRoute: typeof AutoavaliacaoRoute
  ConfiguracaoRoute: typeof ConfiguracaoRoute
  ConteudoRoute: typeof ConteudoRoute
  EnqueteRoute: typeof EnqueteRoute
  EntregaRoute: typeof EntregaRoute
  EquipeRoute: typeof EquipeRoute
  GestaoRoute: typeof GestaoRoute
  HistoricoRoute: typeof HistoricoRoute
  JornadaRoute: typeof JornadaRoute
  ModeracaoRoute: typeof ModeracaoRoute
  PercursoRoute: typeof PercursoRoute
  PerfilRoute: typeof PerfilRoute
  PortfolioRoute: typeof PortfolioRoute
  UnidadeRoute: typeof UnidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoavaliacao': {
      id: '/autoavaliacao'
      path: '/autoavaliacao'
      fullPath: '/autoavaliacao'
      preLoaderRoute: typeof AutoavaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao': {
      id: '/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof ConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquete': {
      id: '/enquete'
      path: '/enquete'
      fullPath: '/enquete'
      preLoaderRoute: typeof EnqueteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderacao': {
      id: '/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof ModeracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percurso': {
      id: '/percurso'
      path: '/percurso'
      fullPath: '/percurso'
      preLoaderRoute: typeof PercursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidade': {
      id: '/unidade'
      path: '/unidade'
      fullPath: '/unidade'
      preLoaderRoute: typeof UnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  AgendaRoute: AgendaRoute,
  AulasRoute: AulasRoute,
  AutoavaliacaoRoute: AutoavaliacaoRoute,
  ConfiguracaoRoute: ConfiguracaoRoute,
  ConteudoRoute: ConteudoRoute,
  EnqueteRoute: EnqueteRoute,
  EntregaRoute: EntregaRoute,
  EquipeRoute: EquipeRoute,
  GestaoRoute: GestaoRoute,
  HistoricoRoute: HistoricoRoute,
  JornadaRoute: JornadaRoute,
  ModeracaoRoute: ModeracaoRoute,
  PercursoRoute: PercursoRoute,
  PerfilRoute: PerfilRoute,
  PortfolioRoute: PortfolioRoute,
  UnidadeRoute: UnidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
